# coding: utf-8

"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dtool_lookup_openapi_client
from dtool_lookup_openapi_client.api.scaffolding_api import ScaffoldingApi  # noqa: E501
from dtool_lookup_openapi_client.rest import ApiException


class TestScaffoldingApi(unittest.TestCase):
    """ScaffoldingApi unit test stubs"""

    def setUp(self):
        self.api = dtool_lookup_openapi_client.api.scaffolding_api.ScaffoldingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_scaffolding_config_get(self):
        """Test case for scaffolding_config_get

        Return the JSON-serialized plugin configuration.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
