# coding: utf-8

"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dtool_lookup_openapi_client
from dtool_lookup_openapi_client.api.config_api import ConfigApi  # noqa: E501
from dtool_lookup_openapi_client.rest import ApiException


class TestConfigApi(unittest.TestCase):
    """ConfigApi unit test stubs"""

    def setUp(self):
        self.api = dtool_lookup_openapi_client.api.config_api.ConfigApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_config_info_get(self):
        """Test case for config_info_get

        Return the JSON-serialized server configuration.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
