# coding: utf-8

"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dtool_lookup_openapi_client
from dtool_lookup_openapi_client.api.graph_api import GraphApi  # noqa: E501
from dtool_lookup_openapi_client.rest import ApiException


class TestGraphApi(unittest.TestCase):
    """GraphApi unit test stubs"""

    def setUp(self):
        self.api = dtool_lookup_openapi_client.api.graph_api.GraphApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_graph_config_get(self):
        """Test case for graph_config_get

        Return the JSON-serialized dependency graph plugin configuration.  # noqa: E501
        """
        pass

    def test_graph_lookup_uuid_get(self):
        """Test case for graph_lookup_uuid_get

        List the datasets within the same dependency graph as <uuid>. If not all datasets are accessible by the user, an incomplete, disconnected graph may arise.  # noqa: E501
        """
        pass

    def test_graph_lookup_uuid_post(self):
        """Test case for graph_lookup_uuid_post

        List the datasets within the same dependency graph as <uuid>. If not all datasets are accessible by the user, an incomplete, disconnected graph may arise.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
