# coding: utf-8

"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import dtool_lookup_openapi_client
from dtool_lookup_openapi_client.api.webhook_api import WebhookApi  # noqa: E501
from dtool_lookup_openapi_client.rest import ApiException


class TestWebhookApi(unittest.TestCase):
    """WebhookApi unit test stubs"""

    def setUp(self):
        self.api = dtool_lookup_openapi_client.api.webhook_api.WebhookApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_webhook_config_get(self):
        """Test case for webhook_config_get

        Return the JSON-serialized plugin configuration.  # noqa: E501
        """
        pass

    def test_webhook_notify_path_post(self):
        """Test case for webhook_notify_path_post

        Notify the lookup server about creation, modification or deletion of a dataset.  # noqa: E501
        """
        pass

    def test_webhook_notify_post(self):
        """Test case for webhook_notify_post

        Notify the lookup server about creation, modification or deletion of a dataset.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
