# coding: utf-8

"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from dtool_lookup_openapi_client.configuration import Configuration


class Manifest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'hash_function': 'str',
        'items': 'dict(str, Item)',
        'dtoolcore_version': 'str'
    }

    attribute_map = {
        'hash_function': 'hash_function',
        'items': 'items',
        'dtoolcore_version': 'dtoolcore_version'
    }

    def __init__(self, hash_function=None, items=None, dtoolcore_version=None, local_vars_configuration=None):  # noqa: E501
        """Manifest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._hash_function = None
        self._items = None
        self._dtoolcore_version = None
        self.discriminator = None

        if hash_function is not None:
            self.hash_function = hash_function
        if items is not None:
            self.items = items
        if dtoolcore_version is not None:
            self.dtoolcore_version = dtoolcore_version

    @property
    def hash_function(self):
        """Gets the hash_function of this Manifest.  # noqa: E501


        :return: The hash_function of this Manifest.  # noqa: E501
        :rtype: str
        """
        return self._hash_function

    @hash_function.setter
    def hash_function(self, hash_function):
        """Sets the hash_function of this Manifest.


        :param hash_function: The hash_function of this Manifest.  # noqa: E501
        :type hash_function: str
        """

        self._hash_function = hash_function

    @property
    def items(self):
        """Gets the items of this Manifest.  # noqa: E501


        :return: The items of this Manifest.  # noqa: E501
        :rtype: dict(str, Item)
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this Manifest.


        :param items: The items of this Manifest.  # noqa: E501
        :type items: dict(str, Item)
        """

        self._items = items

    @property
    def dtoolcore_version(self):
        """Gets the dtoolcore_version of this Manifest.  # noqa: E501


        :return: The dtoolcore_version of this Manifest.  # noqa: E501
        :rtype: str
        """
        return self._dtoolcore_version

    @dtoolcore_version.setter
    def dtoolcore_version(self, dtoolcore_version):
        """Sets the dtoolcore_version of this Manifest.


        :param dtoolcore_version: The dtoolcore_version of this Manifest.  # noqa: E501
        :type dtoolcore_version: str
        """

        self._dtoolcore_version = dtoolcore_version

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Manifest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Manifest):
            return True

        return self.to_dict() != other.to_dict()
