# coding: utf-8

"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from dtool_lookup_openapi_client.configuration import Configuration


class PaginationMetadata(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'total': 'int',
        'total_pages': 'int',
        'first_page': 'int',
        'last_page': 'int',
        'page': 'int',
        'previous_page': 'int',
        'next_page': 'int'
    }

    attribute_map = {
        'total': 'total',
        'total_pages': 'total_pages',
        'first_page': 'first_page',
        'last_page': 'last_page',
        'page': 'page',
        'previous_page': 'previous_page',
        'next_page': 'next_page'
    }

    def __init__(self, total=None, total_pages=None, first_page=None, last_page=None, page=None, previous_page=None, next_page=None, local_vars_configuration=None):  # noqa: E501
        """PaginationMetadata - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._total = None
        self._total_pages = None
        self._first_page = None
        self._last_page = None
        self._page = None
        self._previous_page = None
        self._next_page = None
        self.discriminator = None

        if total is not None:
            self.total = total
        if total_pages is not None:
            self.total_pages = total_pages
        if first_page is not None:
            self.first_page = first_page
        if last_page is not None:
            self.last_page = last_page
        if page is not None:
            self.page = page
        if previous_page is not None:
            self.previous_page = previous_page
        if next_page is not None:
            self.next_page = next_page

    @property
    def total(self):
        """Gets the total of this PaginationMetadata.  # noqa: E501


        :return: The total of this PaginationMetadata.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this PaginationMetadata.


        :param total: The total of this PaginationMetadata.  # noqa: E501
        :type total: int
        """

        self._total = total

    @property
    def total_pages(self):
        """Gets the total_pages of this PaginationMetadata.  # noqa: E501


        :return: The total_pages of this PaginationMetadata.  # noqa: E501
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages):
        """Sets the total_pages of this PaginationMetadata.


        :param total_pages: The total_pages of this PaginationMetadata.  # noqa: E501
        :type total_pages: int
        """

        self._total_pages = total_pages

    @property
    def first_page(self):
        """Gets the first_page of this PaginationMetadata.  # noqa: E501


        :return: The first_page of this PaginationMetadata.  # noqa: E501
        :rtype: int
        """
        return self._first_page

    @first_page.setter
    def first_page(self, first_page):
        """Sets the first_page of this PaginationMetadata.


        :param first_page: The first_page of this PaginationMetadata.  # noqa: E501
        :type first_page: int
        """

        self._first_page = first_page

    @property
    def last_page(self):
        """Gets the last_page of this PaginationMetadata.  # noqa: E501


        :return: The last_page of this PaginationMetadata.  # noqa: E501
        :rtype: int
        """
        return self._last_page

    @last_page.setter
    def last_page(self, last_page):
        """Sets the last_page of this PaginationMetadata.


        :param last_page: The last_page of this PaginationMetadata.  # noqa: E501
        :type last_page: int
        """

        self._last_page = last_page

    @property
    def page(self):
        """Gets the page of this PaginationMetadata.  # noqa: E501


        :return: The page of this PaginationMetadata.  # noqa: E501
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this PaginationMetadata.


        :param page: The page of this PaginationMetadata.  # noqa: E501
        :type page: int
        """

        self._page = page

    @property
    def previous_page(self):
        """Gets the previous_page of this PaginationMetadata.  # noqa: E501


        :return: The previous_page of this PaginationMetadata.  # noqa: E501
        :rtype: int
        """
        return self._previous_page

    @previous_page.setter
    def previous_page(self, previous_page):
        """Sets the previous_page of this PaginationMetadata.


        :param previous_page: The previous_page of this PaginationMetadata.  # noqa: E501
        :type previous_page: int
        """

        self._previous_page = previous_page

    @property
    def next_page(self):
        """Gets the next_page of this PaginationMetadata.  # noqa: E501


        :return: The next_page of this PaginationMetadata.  # noqa: E501
        :rtype: int
        """
        return self._next_page

    @next_page.setter
    def next_page(self, next_page):
        """Sets the next_page of this PaginationMetadata.


        :param next_page: The next_page of this PaginationMetadata.  # noqa: E501
        :type next_page: int
        """

        self._next_page = next_page

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaginationMetadata):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PaginationMetadata):
            return True

        return self.to_dict() != other.to_dict()
