# coding: utf-8

"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from dtool_lookup_openapi_client.configuration import Configuration


class UriPermission(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'users_with_register_permissions': 'list[str]',
        'users_with_search_permissions': 'list[str]',
        'base_uri': 'str'
    }

    attribute_map = {
        'users_with_register_permissions': 'users_with_register_permissions',
        'users_with_search_permissions': 'users_with_search_permissions',
        'base_uri': 'base_uri'
    }

    def __init__(self, users_with_register_permissions=None, users_with_search_permissions=None, base_uri=None, local_vars_configuration=None):  # noqa: E501
        """UriPermission - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._users_with_register_permissions = None
        self._users_with_search_permissions = None
        self._base_uri = None
        self.discriminator = None

        if users_with_register_permissions is not None:
            self.users_with_register_permissions = users_with_register_permissions
        if users_with_search_permissions is not None:
            self.users_with_search_permissions = users_with_search_permissions
        if base_uri is not None:
            self.base_uri = base_uri

    @property
    def users_with_register_permissions(self):
        """Gets the users_with_register_permissions of this UriPermission.  # noqa: E501


        :return: The users_with_register_permissions of this UriPermission.  # noqa: E501
        :rtype: list[str]
        """
        return self._users_with_register_permissions

    @users_with_register_permissions.setter
    def users_with_register_permissions(self, users_with_register_permissions):
        """Sets the users_with_register_permissions of this UriPermission.


        :param users_with_register_permissions: The users_with_register_permissions of this UriPermission.  # noqa: E501
        :type users_with_register_permissions: list[str]
        """

        self._users_with_register_permissions = users_with_register_permissions

    @property
    def users_with_search_permissions(self):
        """Gets the users_with_search_permissions of this UriPermission.  # noqa: E501


        :return: The users_with_search_permissions of this UriPermission.  # noqa: E501
        :rtype: list[str]
        """
        return self._users_with_search_permissions

    @users_with_search_permissions.setter
    def users_with_search_permissions(self, users_with_search_permissions):
        """Sets the users_with_search_permissions of this UriPermission.


        :param users_with_search_permissions: The users_with_search_permissions of this UriPermission.  # noqa: E501
        :type users_with_search_permissions: list[str]
        """

        self._users_with_search_permissions = users_with_search_permissions

    @property
    def base_uri(self):
        """Gets the base_uri of this UriPermission.  # noqa: E501


        :return: The base_uri of this UriPermission.  # noqa: E501
        :rtype: str
        """
        return self._base_uri

    @base_uri.setter
    def base_uri(self, base_uri):
        """Sets the base_uri of this UriPermission.


        :param base_uri: The base_uri of this UriPermission.  # noqa: E501
        :type base_uri: str
        """

        self._base_uri = base_uri

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UriPermission):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UriPermission):
            return True

        return self.to_dict() != other.to_dict()
