# coding: utf-8

"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from dtool_lookup_openapi_client.configuration import Configuration


class UserResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'register_permissions_on_base_uris': 'list[str]',
        'username': 'str',
        'search_permissions_on_base_uris': 'list[str]',
        'is_admin': 'bool'
    }

    attribute_map = {
        'register_permissions_on_base_uris': 'register_permissions_on_base_uris',
        'username': 'username',
        'search_permissions_on_base_uris': 'search_permissions_on_base_uris',
        'is_admin': 'is_admin'
    }

    def __init__(self, register_permissions_on_base_uris=None, username=None, search_permissions_on_base_uris=None, is_admin=None, local_vars_configuration=None):  # noqa: E501
        """UserResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._register_permissions_on_base_uris = None
        self._username = None
        self._search_permissions_on_base_uris = None
        self._is_admin = None
        self.discriminator = None

        if register_permissions_on_base_uris is not None:
            self.register_permissions_on_base_uris = register_permissions_on_base_uris
        if username is not None:
            self.username = username
        if search_permissions_on_base_uris is not None:
            self.search_permissions_on_base_uris = search_permissions_on_base_uris
        if is_admin is not None:
            self.is_admin = is_admin

    @property
    def register_permissions_on_base_uris(self):
        """Gets the register_permissions_on_base_uris of this UserResponse.  # noqa: E501


        :return: The register_permissions_on_base_uris of this UserResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._register_permissions_on_base_uris

    @register_permissions_on_base_uris.setter
    def register_permissions_on_base_uris(self, register_permissions_on_base_uris):
        """Sets the register_permissions_on_base_uris of this UserResponse.


        :param register_permissions_on_base_uris: The register_permissions_on_base_uris of this UserResponse.  # noqa: E501
        :type register_permissions_on_base_uris: list[str]
        """

        self._register_permissions_on_base_uris = register_permissions_on_base_uris

    @property
    def username(self):
        """Gets the username of this UserResponse.  # noqa: E501


        :return: The username of this UserResponse.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UserResponse.


        :param username: The username of this UserResponse.  # noqa: E501
        :type username: str
        """

        self._username = username

    @property
    def search_permissions_on_base_uris(self):
        """Gets the search_permissions_on_base_uris of this UserResponse.  # noqa: E501


        :return: The search_permissions_on_base_uris of this UserResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._search_permissions_on_base_uris

    @search_permissions_on_base_uris.setter
    def search_permissions_on_base_uris(self, search_permissions_on_base_uris):
        """Sets the search_permissions_on_base_uris of this UserResponse.


        :param search_permissions_on_base_uris: The search_permissions_on_base_uris of this UserResponse.  # noqa: E501
        :type search_permissions_on_base_uris: list[str]
        """

        self._search_permissions_on_base_uris = search_permissions_on_base_uris

    @property
    def is_admin(self):
        """Gets the is_admin of this UserResponse.  # noqa: E501


        :return: The is_admin of this UserResponse.  # noqa: E501
        :rtype: bool
        """
        return self._is_admin

    @is_admin.setter
    def is_admin(self, is_admin):
        """Sets the is_admin of this UserResponse.


        :param is_admin: The is_admin of this UserResponse.  # noqa: E501
        :type is_admin: bool
        """

        self._is_admin = is_admin

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserResponse):
            return True

        return self.to_dict() != other.to_dict()
